- name: install maven 
  ansible.builtin.import_role:
    name: common
    tasks_from: maven-setup

- name: setup Application 
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: install dependencies
  ansible.builtin.shell: mvn clean package
  args:
    chdir: /app

- name: rename jar files
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: Load schema  
  ansible.builtin.import_role:
    name: common
    tasks_from: load-mysql-schema

- name: systemd service setup 
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup